name: ros-example
version: 1.0
summary: ROS Example
description: Contains talker/listener ROS packages and a .launch file.
confinement: strict

# Workaround for LP: #1677002.
build-packages: [lsb-release]

apps:
  launch-project:
    command: roslaunch listener talk_and_listen.launch
    plugs: [network-bind]

parts:
  ros-project:
    plugin: catkin
    source: .
    rosdistro: lunar
    catkin-packages:
      - talker
      - listener
    include-roscore: true
